services:
  pgsql:
    image: postgres:latest
    container_name: pgsql
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: envstore